### ISSUE TITLE
After getting the convert token, how to get user's username, email ?

### ISSUE THREAD

**Issue by ibrahimyaacob92** [vladkomudrich/react-django-socialAuth#2]
How to get more data other than access & refresh token after it's being converted by Django ?

**Comment by vladkomudrich** [comment]
You should place access token in each request to get access to different parts of your API.

**Comment by ibrahimyaacob92** [comment]
i understand that, but what if i wanted to get the logged in user's detail using the converted token ?
What Django give me at the moment is pretty useless if i couldnt refer back to who is generating the token..
![image](https://user-images.githubusercontent.com/58116068/116014243-e8f24a80-a666-11eb-8212-7329773d7eac.png)

again It'd be nice if you have an example

**Comment by vladkomudrich** [comment]
Create view which return some user data and create endpoint to send authenticated request with your token. For example:

class CurrentUserView(APIView):
....permission_classes = [IsAuthenticated]
....serializer_class = AccountSerializer

    def get(self, request):
        return Response(data={"user": request.user})
